export const cropsList = [
    "Wheat",
    "Barley",
    "Canola",
    "Cabbage",
    "Cauliflower",
    "Broccoli",
    "Brussels sprouts",
    "Kale",
    "Collard greens",
    "Mustard greens",
    "Spinach",
    "Swiss chard",
    "Lettuce",
    "Arugula",
    "Radishes",
    "Beets",
    "Carrots",
    "Turnips",
    "Parsnips",
    "Potatoes",
    "Sweet potatoes",
    "Onions",
    "Garlic",
    "Chickpeas",
    "Faba beans",
    "Field peas",
    "Lentils",
    "Lupins",
    "Oats",
    "Triticale",
    "Grain sorghum",
    "Cottonseed",
    "Cotton lint",
    "Rice",
    "Corn (maize)",
    "Soybeans",
    "Sunflower",
    "Sugarcane",
    "Potatoes",
    "Sweet corn",
    "Alfalfa",
    "Millet",
    "Safflower",
    "Flaxseed",
    "Pigeon peas",
    "Mung beans",
    "Chia",
    "Pumpkins",
    "Carrots",
    "Tobacco",
    "Quinoa",
    "Hemp",
    "Beetroot"
  ];

export type CropName = typeof cropsList[number];

export interface CropAttributes {
  optimalTempRangeC: [number, number];        // Min and max optimal temperature in °C
  rainfallCorrelation: number;                // Correlation coefficient with yield (-1 to 1)
  snowCorrelation: number;                    // Correlation coefficient with yield (-1 to 1)
  pestSensitivity: number;                    // Sensitivity to pests (0 low – 1 high)
}

export const cropAttributes = {
  Wheat:               { optimalTempRangeC: [12, 25], rainfallCorrelation: 0.7,  snowCorrelation: -0.2, pestSensitivity: 0.6 },
  Barley:              { optimalTempRangeC: [10, 20], rainfallCorrelation: 0.6,  snowCorrelation: -0.1, pestSensitivity: 0.5 },
  Canola:              { optimalTempRangeC: [8, 23],  rainfallCorrelation: 0.8,  snowCorrelation: -0.3, pestSensitivity: 0.7 },
  Cabbage:             { optimalTempRangeC: [10, 18], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.4 },
  Cauliflower:         { optimalTempRangeC: [15, 20], rainfallCorrelation: 0.6,  snowCorrelation: -0.1, pestSensitivity: 0.5 },
  Broccoli:            { optimalTempRangeC: [15, 23], rainfallCorrelation: 0.6,  snowCorrelation: -0.1, pestSensitivity: 0.5 },
  "Brussels sprouts":  { optimalTempRangeC: [12, 18], rainfallCorrelation: 0.4,  snowCorrelation: -0.3, pestSensitivity: 0.4 },
  Kale:                { optimalTempRangeC: [15, 20], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.3 },
  "Collard greens":    { optimalTempRangeC: [15, 25], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.3 },
  "Mustard greens":    { optimalTempRangeC: [10, 20], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.4 },
  Spinach:             { optimalTempRangeC: [10, 16], rainfallCorrelation: 0.6,  snowCorrelation: -0.2, pestSensitivity: 0.6 },
  "Swiss chard":       { optimalTempRangeC: [15, 21], rainfallCorrelation: 0.6,  snowCorrelation: -0.2, pestSensitivity: 0.4 },
  Lettuce:             { optimalTempRangeC: [15, 18], rainfallCorrelation: 0.5,  snowCorrelation: -0.1, pestSensitivity: 0.5 },
  Arugula:             { optimalTempRangeC: [10, 20], rainfallCorrelation: 0.4,  snowCorrelation: -0.2, pestSensitivity: 0.3 },
  Radishes:            { optimalTempRangeC: [16, 24], rainfallCorrelation: 0.3,  snowCorrelation: -0.1, pestSensitivity: 0.3 },
  Beets:               { optimalTempRangeC: [15, 18], rainfallCorrelation: 0.5,  snowCorrelation: -0.1, pestSensitivity: 0.4 },
  Carrots:             { optimalTempRangeC: [16, 21], rainfallCorrelation: 0.6,  snowCorrelation: -0.1, pestSensitivity: 0.4 },
  Turnips:             { optimalTempRangeC: [10, 18], rainfallCorrelation: 0.5,  snowCorrelation: -0.1, pestSensitivity: 0.4 },
  Parsnips:            { optimalTempRangeC: [10, 18], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.4 },
  Potatoes:            { optimalTempRangeC: [15, 18], rainfallCorrelation: 0.7,  snowCorrelation: -0.1, pestSensitivity: 0.5 },
  "Sweet potatoes":    { optimalTempRangeC: [20, 30], rainfallCorrelation: 0.6,  snowCorrelation: -0.5, pestSensitivity: 0.6 },
  Onions:              { optimalTempRangeC: [13, 24], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.5 },
  Garlic:              { optimalTempRangeC: [13, 24], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.4 },
  Chickpeas:           { optimalTempRangeC: [16, 30], rainfallCorrelation: 0.4,  snowCorrelation: -0.3, pestSensitivity: 0.5 },
  "Faba beans":        { optimalTempRangeC: [18, 24], rainfallCorrelation: 0.6,  snowCorrelation: -0.3, pestSensitivity: 0.5 },
  "Field peas":        { optimalTempRangeC: [10, 18], rainfallCorrelation: 0.6,  snowCorrelation: -0.2, pestSensitivity: 0.5 },
  Lentils:             { optimalTempRangeC: [10, 22], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.4 },
  Lupins:              { optimalTempRangeC: [15, 25], rainfallCorrelation: 0.6,  snowCorrelation: -0.2, pestSensitivity: 0.5 },
  Oats:                { optimalTempRangeC: [10, 20], rainfallCorrelation: 0.6,  snowCorrelation: -0.1, pestSensitivity: 0.4 },
  Triticale:           { optimalTempRangeC: [12, 20], rainfallCorrelation: 0.6,  snowCorrelation: -0.1, pestSensitivity: 0.5 },
  "Grain sorghum":     { optimalTempRangeC: [20, 32], rainfallCorrelation: 0.7,  snowCorrelation: -0.5, pestSensitivity: 0.6 },
  Cottonseed:          { optimalTempRangeC: [20, 30], rainfallCorrelation: 0.5,  snowCorrelation: -0.5, pestSensitivity: 0.7 },
  "Cotton lint":       { optimalTempRangeC: [20, 30], rainfallCorrelation: 0.5,  snowCorrelation: -0.5, pestSensitivity: 0.7 },
  Rice:                { optimalTempRangeC: [20, 30], rainfallCorrelation: 0.8,  snowCorrelation: -0.5, pestSensitivity: 0.6 },
  "Corn (maize)":      { optimalTempRangeC: [18, 27], rainfallCorrelation: 0.8,  snowCorrelation: -0.3, pestSensitivity: 0.6 },
  Soybeans:            { optimalTempRangeC: [20, 30], rainfallCorrelation: 0.7,  snowCorrelation: -0.3, pestSensitivity: 0.5 },
  Sunflower:           { optimalTempRangeC: [20, 25], rainfallCorrelation: 0.6,  snowCorrelation: -0.5, pestSensitivity: 0.4 },
  Sugarcane:           { optimalTempRangeC: [20, 35], rainfallCorrelation: 0.8,  snowCorrelation: -0.8, pestSensitivity: 0.5 },
  "Sweet corn":        { optimalTempRangeC: [18, 25], rainfallCorrelation: 0.7,  snowCorrelation: -0.3, pestSensitivity: 0.6 },
  Alfalfa:             { optimalTempRangeC: [10, 30], rainfallCorrelation: 0.6,  snowCorrelation: -0.2, pestSensitivity: 0.4 },
  Millet:              { optimalTempRangeC: [25, 35], rainfallCorrelation: 0.4,  snowCorrelation: -0.5, pestSensitivity: 0.5 },
  Safflower:           { optimalTempRangeC: [15, 30], rainfallCorrelation: 0.4,  snowCorrelation: -0.3, pestSensitivity: 0.5 },
  Flaxseed:            { optimalTempRangeC: [18, 25], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.5 },
  "Pigeon peas":       { optimalTempRangeC: [20, 30], rainfallCorrelation: 0.4,  snowCorrelation: -0.5, pestSensitivity: 0.6 },
  "Mung beans":        { optimalTempRangeC: [20, 30], rainfallCorrelation: 0.5,  snowCorrelation: -0.5, pestSensitivity: 0.5 },
  Chia:                { optimalTempRangeC: [16, 30], rainfallCorrelation: 0.4,  snowCorrelation: -0.5, pestSensitivity: 0.4 },
  Pumpkins:            { optimalTempRangeC: [18, 24], rainfallCorrelation: 0.6,  snowCorrelation: -0.3, pestSensitivity: 0.7 },
  Tobacco:             { optimalTempRangeC: [20, 30], rainfallCorrelation: 0.5,  snowCorrelation: -0.4, pestSensitivity: 0.6 },
  Quinoa:              { optimalTempRangeC: [10, 25], rainfallCorrelation: 0.5,  snowCorrelation: -0.2, pestSensitivity: 0.4 },
  Hemp:                { optimalTempRangeC: [15, 27], rainfallCorrelation: 0.6,  snowCorrelation: -0.3, pestSensitivity: 0.5 },
  Beetroot:            { optimalTempRangeC: [10, 21], rainfallCorrelation: 0.6,  snowCorrelation: -0.1, pestSensitivity: 0.5 },
};