export const crops: string[] = [
    "Wheat",
    "Barley",
    "Canola",
    "Chickpeas",
    "Faba beans",
    "Field peas",
    "Lentils",
    "Lupins",
    "Oats",
    "Triticale",
    "Grain sorghum",
    "Cottonseed",
    "Cotton lint",
    "Rice",
    "Corn (maize)",
    "Soybeans",
    "Sunflower",
    "Sugarcane",
    "Potatoes",
    "Sweet corn",
    "Alfalfa",
    "Millet",
    "Safflower",
    "Flaxseed",
    "Pigeon peas",
    "Mung beans",
    "Chia",
    "Pumpkins",
    "Carrots",
    "Tobacco",
    "Quinoa",
    "Hemp",
    "Beetroot"
  ];